= A Profile for Jim
jimi@idle.ws
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

A professional programmer for many years.

I have been a member of open source projects since before Github was a thing. I have accumulated many skills in backend
and technical programming. From the arcane to the very popular.

Currently most work is in Go, though I can work in just about any computer language.

== My Current Opensource Work

=== ANTLR Parser Generator

ANTLR (_ANother Tool for Language Recognition_) is a powerful parser generator for reading, processing, executing, or
translating structured text or binary files. It's widely used to build languages, tools, and frameworks. I wrote the
code generator and runtime for `C`, for version 3 of the toolset. I now work on the code generator and runtime for
`Go` for version 4.

  - https://github.com/antlr/antlr4[The ANTLR Project]
  - https://github.com/antlr/antlr4/tree/master/runtime/Go/antlr/v4[The Go runtime for ANTLR4]

=== JWZ - An algorithm for threading email

JWZ was the original algorithm in Mozilla, for arranging email into threads. It was originally devised by Jamie Zawinski, and
https://github.com/gatherstars-com/jwz[this] is my improved implementation in Go.

== Languages

Go, C, C++, Java, Shell, Python, SQL, XML, Assembly language, Typescript, sed, awk ...

== Technologies

  - *_AWS_*: Lambda, Serverless, S3, DynamoDB, SQS, SNS, CloudWatch, IAM, API Gateway, ECS, ECR, EKS, Aurora, Neptune,
Architecture as code, CDK, scalability, metrics ...
  - Database engines, database design ...
  - Compilers, parsers, codegen, interpreters, VM/byte code ...
  - DSL design, DSL implementation, DSL execution ...
  - API design, API implementation, API execution, REST, GraphQL ...
  - Message based architectures, messaging, message queues, message brokers, message routing, message transformation ...
  - Linux, Windows, Mac, Unix, BSD, Solaris, AIX, HP-UX, ...
